# Generated by Django 5.0.6 on 2025-03-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IgniteStudyApp", "0002_userprofile_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("grade", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("subject", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
